language: java

dist: trusty
addons:
  chrome: stable
before_script:
  - mvn spring-boot:run &
  - sleep 10 && google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:8080 &